name-template: '$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
prerelease: false
categories:
  - title: 🚀 BPMN support
    labels:
      - BPMN support
  - title: 🚄 BPMN rendering
    labels:
      - BPMN rendering
  - title: 🧲 BPMN diagram usability
    labels:
      - 'BPMN diagram usability'
  - title: ⛵ BPMN diagram navigation
    labels:
      - 'BPMN diagram navigation'
  - title: ✍ BPMN diagram overlays
    labels:
      - 'BPMN diagram overlays'
  - title: 🌈 BPMN diagram styling
    labels:
      - 'BPMN diagram styling'
  - title: 🐛 Bug Fixes
    labels:
      - bug
  - title: 🦾 Robustness
    labels:
      - 'robustness'
  - title: ⤵️ Library Integration
    labels:
      - 'lib integration'
  - title: ↔️ Library Extensibility
    labels:
      - 'lib extensibility'
  - title: 📝 Documentation
    label: documentation
  - title: 🎮 Demo and Examples
    label: example
  - title: 👻 Maintenance
    labels:
      - infra:build
      - infra:refactoring
      - infra:repo
      - chore
      - internal
  - title: 📦 Dependency updates
    labels:
      - dependencies
exclude-labels:
  - invalid
  - no-changelog
  - skip-changelog
  - reverted
  - wontfix
template: |
  **TODO: add a short description about the release content - important for url preview**
  This new release focuses on .... **or something similar**


  **TODO: review the contributors list (remove ALL bots and avoid duplicates)**
  Thanks to all the contributors of this release 🌈: $CONTRIBUTORS

  **TODO: add milestone id when publishing**
  See [milestone $NEXT_PATCH_VERSION](https://github.com/process-analytics/bpmn-visualization-js/milestone/x?closed=1) to get the list of issues covered by this release.

  # Highlights

  **TODO: add screenshots and user oriented info**

  # What's Changed
  $CHANGES

  **TODO: check previous and next tag in the link below**
  
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$NEXT_PATCH_VERSION

replacers:
  - search: '@dependabot-preview'
    replace: '@dependabot'
  - search: '@dependabot[bot]'
    replace: '@dependabot'
