name-template: '$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
prerelease: false
categories:
  - title: 🚀 BPMN support
    labels:
      - BPMN support
  - title: 🚄 BPMN rendering
    labels:
      - BPMN rendering
  - title: 🧲 BPMN diagram usability
    labels:
      - 'BPMN diagram usability'
  - title: ⛵ BPMN diagram navigation
    labels:
      - 'BPMN diagram navigation'
  - title: ✍ BPMN diagram overlays
    labels:
      - 'BPMN diagram overlays'
  - title: 🌈 BPMN diagram styling
    labels:
      - 'BPMN diagram styling'
  - title: 🐛 Bug Fixes
    labels:
      - bug
  - title: 🦾 Robustness
    labels:
      - 'robustness'
  - title: ⤵️ Library Integration
    labels:
      - 'lib integration'
  - title: ↔️ Library Extensibility
    labels:
      - 'lib extensibility'
  - title: 📝 Documentation
    label: documentation
  - title: 🎮 Demo and Examples
    label: example
  - title: 📦 Dependency updates
    labels:
      - dependencies
  - title: 👻 Maintenance
    labels:
      - chore
      - refactoring
exclude-labels:
  - skip-changelog
# Exclude specific usernames from the generated $CONTRIBUTORS variable.
# https://github.com/release-drafter/release-drafter/tree/master#exclude-contributors
exclude-contributors:
  - 'dependabot'
  - 'dependabot[bot]'
  - 'process-analytics-bot'
template: |
  **TODO: add a short description about the release content - important for url preview**
  This new release focuses on .... **or something similar**
  This new version brings improvements to ...

  **TODO: review the contributors list (remove ALL bots and avoid duplicates)**
  Thanks to all the contributors of this release 🌈: $CONTRIBUTORS

  **TODO: use the right milestone id and ensure the version is the right one**
  See [milestone $NEXT_PATCH_VERSION](https://github.com/$OWNER/$REPOSITORY/milestone/x?closed=1) to get the list of issues covered by this release.

  **TODO: check previous and next tag in the "full changelog" link in the "What's changed section"**

  # Highlights

  **TODO: add screenshots and user oriented info**

  **TODO: highlight changes from the `examples` repository**
  Important updates and/or new features may be available in this repository and are worth mentioning.
  In this case:
    - release the `examples` repository first
    - add a link to the RN https://github.com/$OWNER/bpmn-visualization-examples/releases/tag/v0.34.0
  Optional: add link to the live statically.io environment including the tag (not the `master` branch) 

  ## Breaking Changes

  **TODO: keep if releavant and follow the guidelines below**

  - explain the impact (use case)
  - this includes the removal of deprecated

  ### Removal of deprecated API

  - list API
  - add reference to the version and release notes where it was announced as "deprecated"
  
  ## Deprecated APIs

  **TODO: keep if releavant and follow the guidelines below**

  - list the APIs
  - explain why they are deprecated
  - provide the new API to use instead. If none exist, mention it
  - explain in which version it will be removed. We usually keep 3 minor versions prior removal.
  - ensure that an issue exists to track the removal (one by version is OK) and it is attached to a milestone related to the version 

  ## External Contributions

  We are excited to include the following external contributions in this release:
  <!-- list contributions here -->

  ### Contrib 1  

  Description.

  ℹ️ You can find more details about this contribution in #XXX.


  # What's Changed

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$NEXT_PATCH_VERSION

  $CHANGES
