=== BPMN Support - How To
:icons: font

==== Elements detection

Except for special container elements like `Pool`, `Lane` and `Subprocess`, detecting a new BPMN element only requires to
add a new value in the `ShapeBpmnElementKind` enum.

The `ProcessConverter` uses the `ShapeBpmnElementKind` values to detect elements in the BPMN source.

===== Elements requiring special attention 

- For BPMN Events, the actual type in controlled by `EventDefinition` fields in the BPMN specification. Detecting new event
types requires changes in `ShapeBpmnEventKind` to add the newly supported BPMN Event Definition.
- For BPMN SubProcesses, the actual type is controlled by `ShapeBpmnSubProcessKind` which is set accordingly during the BPMN parsing.

===== Tests for elements detection 

[IMPORTANT]
Do not forget to add tests related to the new BPMN element to ensure everything works fine.

*Test guidelines:*

* Add json parsing tests related to the new BPMN element to ensure that the parser is able to make it available to the
`ProcessConverter`. The convention is to have a test file per BPMN element, please follow the existing file name scheme.
* Depending on the BPMN element, you may also have to add tests about `default sequence flow` and/or `conditional sequence
flow` support (see `ShapeBpmnElementKind` for more details)
* Add end-to-end tests, mainly to ensure that the new BPMN element is now stored in the `mxGraph model`, see `mxGraph.model.test.ts`.
* No need to create specific XML tests, the XML parsing is tested globally using BPMN files for various BPMN vendors.

[[bpmn-support-howto-elements-rendering]]
==== Elements rendering

When inserting an element on the `mxGraph` graph, a style is passed to identify the way it will be rendered.

The https://jgraph.github.io/mxgraph/docs/js-api/files/view/mxStylesheet-js.html[style] is defined and registered in
`StyleConfigurator`. In particular, it refers to the name of a https://jgraph.github.io/mxgraph/docs/js-api/files/shape/mxShape-js.html[mxShape]
used for the rendering.

The `mxShape` can be a standard `mxGraph` class or a custom BPMN `mxShape` defined by the lib. The custom `mxShapes` are registered by `ShapeConfigurator`
which associates the `mxShape` name (used in style definition) with the `mxShape` class to be used.


===== BPMN icon tips

The icon of the BPMN elements must be defined in the mxGraph custom shapes and this currently must be done using `TypeScript`
code.

It is possible to adapt an SVG icon thanks to https://github.com/process-analytics/mxgraph-svg2shape[mxgraph-svg2shape],
a Java tool that will let you transform your SVG file into a set of `TypeScript` commands.

Please be aware that the tool is not able to support all SVG files, and you may need to adapt the SVG definition prior the
tool can transform it. See https://github.com/process-analytics/bpmn-visualization-js/pull/210[PR #210] for instance.
