=== BPMN Support - How To
:icons: font

==== Elements detection

Except for special container elements like `Pool`, `Lane` and `Subprocess`, detecting a new BPMN element only requires to
add a new value in the `ShapeBpmnElementKind` enum.

The `ProcessConverter` uses the `ShapeBpmnElementKind` values to detect elements in the BPMN source.

[NOTE]
For BPMN Events, the actual type in controlled by `EventDefinition` fields in the BPMN specification. Detecting new event
types requires changes in `ShapeBpmnEventKind` to add the newly supported BPMN Event Definition.

[IMPORTANT]
Do not forget to add json parsing tests related to the new BPMN element to ensure that the parser is able to
make it available to the `ProcessConverter`. The convention is to have a test file per BPMN element, please follow the
existing file name scheme.
No need to create specific XML tests when adding new BPMN elements support.


==== Elements rendering

When inserting an element on the graph, a style is passed to identify the way it will be rendered.

The https://jgraph.github.io/mxgraph/docs/js-api/files/view/mxStylesheet-js.html[style] is defined and registered in
`StyleConfigurator`. In particular, it refers to the name of a https://jgraph.github.io/mxgraph/docs/js-api/files/shape/mxShape-js.html[mxShape]
used for the rendering.

The `mxShape` can be a standard `mxGraph` class or a custom BPMN `mxShape` defined by the lib. The custom `mxShapes` are registered by `ShapeConfigurator`
which associates the `mxShape` name (used in style definition) with the `mxShape` class to be used.
