=== mxGraph Integration

The https://jgraph.github.io/mxgraph/[mxGraph] integration is in charge of displaying the BPMN diagrams, by filling the
https://jgraph.github.io/mxgraph/docs/manual.html#3.1.1:[mxGraph model] from the BPMN model.

It defines the https://jgraph.github.io/mxgraph/docs/manual.html#3.1.3.1[BPMN styles] including dedicated BPMN shapes
which are associated to the `mxGraph` https://jgraph.github.io/mxgraph/docs/manual.html#3.1.3.4[mxCell] when the elements
are inserted into the `mxGraph` model:

* `vertex` for BPMN Shapes
* `edge` for BPMN Edges

For more technical details, see the <<bpmn-support-howto-elements-rendering,BPMN Elements rendering>>

==== BPMN elements positioning

*WIP*
Apply to both BPMN shapes and edges

* mxGraph coordinates: relative to parent
* BPMN: absolute

--> required a transformation layer


==== Logical Groups of BPMN Elements

https://jgraph.github.io/mxgraph/docs/manual.html#3.1.4[mxGraph group structure] allows to define a parent-child relationship
that leverages various rendering feature like collapse/expand, group move/hide, ...
The following group of BPMN elements are created

* `pool` is the parent of `lanes` and `inter-lane elements` (for instance, `message flows`)
* `lane` is the parent of elements it includes in the BPMN source

The default mxGraph parent is the parent of

* inter pool elements ( (for instance, `message flows)`)
* elements when the the BPMN source doesn't define any lane/pool
