name: 'Build Setup'
description: 'Setup node'
runs:
  using: "composite"
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    - name: Install dependencies
      env:
        # https://playwright.dev/docs/browsers#installing-browsers
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      run: npm ci
