name: 'Build Setup'
description: 'Setup node and install dependencies'
inputs:
  install-dependencies:
    description: 'Install dependencies with npm.'
    required: false
    default: 'true'
  registry-url:
    description: 'Optional registry to set up for auth.'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        registry-url: ${{ inputs.registry-url }}
    - name: Install dependencies
      uses: bahmutov/npm-install@v1
      if: inputs.install-dependencies == 'true'
      with:
        install-command: npm ci --ignore-scripts --prefer-offline --audit false
