== Introduction

`bpmn-visualization` is a TypeScript library to visualize process execution data on https://www.omg.org/spec/BPMN/2.0.2/[BPMN]
diagrams. It is in early development stages and is subject to changes prior to the `1.0.0` release.

For now, we render the most <<supported-bpmn-elements,common BPMN elements>>. Notice that there is currently no plan to support `Conversation` and `Choreography`.

We are currently focusing on the https://github.com/process-analytics/bpmn-visualization-js/milestone/18[packaging] of the library.

Then, we will work on BPMN extensions, library extension points, display options for execution data with interactive
capacities.

**Supported Browsers**: Chrome, Firefox, Safari, Edge.


== Demo and examples

=== Demo
Give a try to the https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/master/demo/index.html[**icon:forward[] demo live environment**].
The demo let you load a BPMN file to see how `bpmn-visualization` renders it. Various versions of the lib are available.

If you need BPMN examples, you can use resources from

* the http://www.omgwiki.org/bpmn-miwg[BPMN Model Interchange Working Group (BPMN MIWG)]
** https://github.com/bpmn-miwg/bpmn-miwg-test-suite
** https://github.com/bpmn-miwg/bpmn-miwg-demos
* https://github.com/process-analytics/bpmn-visualization-examples/blob/master/bpmn-files/README.md[bpmn-visualization BPMN test diagrams] 


=== Examples
Want to know more about `bpmn-visualization` usage and extensibility? Have a look at the
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/master/examples/index.html[**icon:forward[] examples live environment**].

For more technical details and how-to, go to the https://github.com/process-analytics/bpmn-visualization-examples/[bpmn-visualization-examples]
repository.
