name: 'Custom surge preview'
description: 'Simplify usage of surge-preview'
inputs:
  artifact-name:
    description: 'The name of the artifact that is uploaded when it is not possible to deploy to surge'
    required: true
  build-preview-command:
    description: 'The command to build the preview'
    required: true
  build-preview-dist:
    description: 'The dist folder deployed to surge.sh'
    required: true
  github-token:
    description: 'A token with `pull-requests: write` to let the surge-preview action create comments on pull requests'
    required: true
  surge-token:
    description: 'A surge token to manage the deployment'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: bonitasoft/actions/packages/surge-preview-tools@v2
      id: surge-preview-tools
      with:
        surge-token: ${{ inputs.surge-token }}
    - uses: actions/checkout@v3
      if: github.event.action != 'closed'
    - name: Build Setup
      uses: ./.github/actions/build-setup
      if: github.event.action != 'closed'
    - name: Build preview
      if: github.event.action != 'closed'
      shell: bash
      run: ${{ inputs.build-preview-command }}
    - name: Manage surge preview
      if: steps.surge-preview-tools.outputs.can-run-surge-command == 'true'
      uses: afc163/surge-preview@v1
      with:
        surge_token: ${{ inputs.surge-token }}
        github_token: ${{ inputs.github-token }}
        dist: ${{ inputs.build-preview-dist }}
        failOnError: true
        teardown: 'true'
        build: echo 'already built!'
    # Fallback when it is not possible to deploy to surge
    - name: Upload artifact (preview not deployed)
      if: github.event.action != 'closed' && steps.surge-preview-tools.outputs.can-run-surge-command == 'false'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}-${{github.sha}}
        path: ${{ inputs.build-preview-dist }}
