# This ensures that the tests can run
name: Run Performance Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '* 3 * * 0'
  pull_request:
    branches:
      - master
    paths:
      - '.github/actions/build-setup/**/*'
      - '.github/workflows/test-performance.yml'
      - 'test/performance/**/*'

jobs:
  test_performance:
    runs-on: ${{ matrix.os }}
    strategy:
      # we want to run the full build on all os: don't cancel running jobs even if one fails
      fail-fast: false
      matrix:
        # disable windows-2019 in a first implementation as it always fails. Require more investigations.
        # node:internal/process/promises:279
        #            triggerUncaughtException(err, true /* fromPromise */);
        #            ^
        # cdpSession.detach: Browser closed.
        os: [macos-12, ubuntu-20.04]
    env:
      # Performance tests rely on chromium API
      browser: chromium
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Setup
        uses: ./.github/actions/build-setup
      # install OS dependencies required by browsers on the GitHub runner
      # to be sure that the browser is correctly installed: https://github.com/microsoft/playwright/issues/5801
      - name: Install ${{env.browser}} and its dependencies only
        run: |
          npx playwright install ${{env.browser}}
          npx playwright install-deps ${{env.browser}}
      - name: Run performance tests
        id: 'run_perf_tests'
        run: npm run test:perf
      - name: Upload test results
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: perf-test-results-${{matrix.os}}-${{github.sha}}
          path: |
            test/performance/index.html
            test/performance/data/
